spring.application.name=springBackEndUniversidad
#=========================================
#* ruta para el versionado de la aplicación *
#=========================================
server.servlet.context-path=/api/v1

#==================================================
#**Configuración personalizada de la aplicación ***
#==================================================
app.name=Sistema de Inscripción de Materias
app.version=1.0.0
app.autor=Devs 
app.language=es
app.country=SV
app.support.email=soporte@ulaes.edu.sv
app.base.url=https://ulaes.edu.sv

#=========================================
#********** BASE DE DATOS ************+***
#=========================================
spring.datasource.url=jdbc:mysql://localhost:3306/ulaesDB
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddlAuto=update

# ==========================
# DATABASE CONNECTION
# ==========================
#spring.datasource.url=jdbc:mysql://projectdb-26dace5e-limtu-c504.k.aivencloud.com:23672/defaultdb?sslMode=REQUIRED
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_8vNkLXgBRlUZxnkKNlm
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


#=========================================
#*************** JWT ************+********
#=========================================
#JWT link= https://jwtsecrets.com/tools/encryption-key-generator
jwt.secret.key=080114d04ccdcf360376d885958dffce33cc9f321308454a067d2daa6442eb3e
#time expiration of 1 day(86400000)       4 horas(14400000)
jwt.time.expiration=86400000

#= ============================================
#=CONFIGURACIÓN DE EMAIL
#= ============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luiseramosramos2122@gmail.com
spring.mail.password=ynqkoeujhjonfhiv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#=========================================
#*** habilitamos el manejo de archivos*******
#=========================================
spring.servlet.multipart.enabled=true
#tamaño maximo en los archivos
spring.servlet.multipart.max-file-size=10MB
#tamaño maximo que se hará por cada petición
spring.servlet.multipart.max-request-size=10MB

#=========================================
#****Configuración de almacenamiento de PDFs ********
#=========================================
app.pdf.storage.path=reportes/inscripciones
app.pdf.base-url=http://localhost:8080

#=========================================
#****  swagger-ui custom path  **+********
#=========================================
#para entrar a la url de swagger
#http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

#=========================================
#*************** Logging ************+********
#=========================================
logging.level.root=INFO
logging.level.com.springApp=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

